name: Grow cactus

on: 
  schedule:
    - cron: '0 0 * * *'

jobs:
  water:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Grow
        run: echo '<br/>🌵' >> README.md
      
      - name: Add identification
        run: |
          git config user.email "yanwl.note@gmail.com"
          git config user.name "yan-wl"

      - name: Commit
        run: |
          git add README.md
          git commit -m "Grow plant"

      - name: Push
        run: |
          git push
