name: Update image

on: 
  schedule:
    - cron: '0 * * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update
        env:
          HCTI_USER_ID: ${{ secrets.HCTI_USER_ID }}
          HCTI_API_KEY: ${{ secrets.HCTI_API_KEY }}
        run: |
          gcc generate.c -o generate.o
          gcc convert.c -o convert.o
          ./generate.o | ./convert.o | ./create.sh > README.md
      
      - name: Add identification
        run: |
          git config user.email "yanwl.note@gmail.com"
          git config user.name "yan-wl"

      - name: Commit
        run: |
          git add README.md
          git commit -m "Grow plant"

      - name: Push
        run: |
          git push
